# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: animation.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import effects_pb2 as effects__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='animation.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0f\x61nimation.proto\x1a\reffects.proto\"r\n\x13TimedAnimationProto\x12\"\n\tanimation\x18\x01 \x01(\x0b\x32\x0f.AnimationProto\x12\x14\n\x0ctrigger_name\x18\x02 \x01(\t\x12!\n\x19start_time_ms_since_ephoc\x18\x03 \x01(\x04\x62\x06proto3'
  ,
  dependencies=[effects__pb2.DESCRIPTOR,])




_TIMEDANIMATIONPROTO = _descriptor.Descriptor(
  name='TimedAnimationProto',
  full_name='TimedAnimationProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='animation', full_name='TimedAnimationProto.animation', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='trigger_name', full_name='TimedAnimationProto.trigger_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='start_time_ms_since_ephoc', full_name='TimedAnimationProto.start_time_ms_since_ephoc', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=148,
)

_TIMEDANIMATIONPROTO.fields_by_name['animation'].message_type = effects__pb2._ANIMATIONPROTO
DESCRIPTOR.message_types_by_name['TimedAnimationProto'] = _TIMEDANIMATIONPROTO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TimedAnimationProto = _reflection.GeneratedProtocolMessageType('TimedAnimationProto', (_message.Message,), {
  'DESCRIPTOR' : _TIMEDANIMATIONPROTO,
  '__module__' : 'animation_pb2'
  # @@protoc_insertion_point(class_scope:TimedAnimationProto)
  })
_sym_db.RegisterMessage(TimedAnimationProto)


# @@protoc_insertion_point(module_scope)
